// Code generated by go-bindata.
// sources:
// templates/network.tf
// templates/output.tf
// templates/provider.tf
// templates/resource_group.tf
// templates/vars.tf
// DO NOT EDIT!

package webserver

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _templatesNetworkTf = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xec\x91\xcf\x4e\xf3\x30\x10\xc4\xef\x7e\x8a\x91\xbf\x1e\x3e\x44\x09\x2d\x07\xc4\xa5\x27\x1e\xa3\xaa\x22\x37\xde\x82\xa1\xb5\xa3\xb5\x5d\x2a\xa2\xbc\x3b\xca\x9f\x56\xc4\x4d\x41\x88\x2b\xc9\xc9\xde\xd9\x1d\xcf\x6f\xff\xe1\x91\x49\x05\x82\xc2\xde\x70\x88\x6a\x0b\x4b\xe1\xcd\xf1\x2b\x8c\x45\x78\x26\x68\xda\xa8\xb8\x0d\x60\xf2\x2e\x72\x41\x78\x62\x17\x4b\x71\x3a\x4a\xf5\x1e\x99\x78\x97\xf7\xfd\x79\xdf\x2f\x21\x5f\x8c\xd5\x2e\x9e\x17\x2a\x01\x58\xb5\x23\x24\xdf\xe2\xd8\x22\x05\x4e\x7e\x79\xeb\x97\xb7\xfa\x05\xe4\xa4\x3a\xfa\x0d\x05\x59\x6f\x96\xdc\x36\x6d\x75\x33\x4e\x69\xcd\xe4\x7d\xee\x4b\x55\xd0\xc9\x6f\x29\xe7\xb3\xac\xfd\x6f\xe7\xf7\x72\x25\x80\xad\x2b\x54\x30\xce\x26\xef\x9a\x54\x7b\xc5\xd9\xb1\x58\x4b\x51\x8b\x11\x04\x3e\xae\x2d\x85\x26\x79\xdc\x95\x6b\x77\xb8\x1c\xb5\xcd\xda\x8b\x2e\x84\xfd\x4d\xda\x04\xf9\x08\xbd\x44\x91\x8d\xef\xea\x9c\x5f\xc9\xb4\x31\x87\xcf\x60\x0a\xa3\xb9\x0b\xfe\xff\x87\xc3\x07\x3b\x59\xce\x56\x53\x3c\x4c\x31\xbb\xfa\x9e\x6e\x37\xae\x3b\xfb\xaf\x21\x77\xa2\x9b\x49\x55\xb8\x68\x43\x66\xac\xa6\x03\xae\x31\xaf\xff\xb0\x0f\xb0\x27\x78\x9a\x25\x08\x74\xb7\x58\xe0\x4e\xd4\xe2\x23\x00\x00\xff\xff\xf5\x3c\x1b\x65\x2b\x04\x00\x00")

func templatesNetworkTfBytes() ([]byte, error) {
	return bindataRead(
		_templatesNetworkTf,
		"templates/network.tf",
	)
}

func templatesNetworkTf() (*asset, error) {
	bytes, err := templatesNetworkTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/network.tf", size: 1067, mode: os.FileMode(480), modTime: time.Unix(1540863722, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _templatesOutputTf = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xa4\xcd\xc1\x4a\x03\x31\x10\xc6\xf1\x7b\x9e\x22\x04\x0f\x0a\xb2\xe0\xc5\x9b\xcf\x12\xd2\x66\xac\xa9\x9b\x99\x30\x99\x49\x8b\xa5\xef\x2e\x75\x59\x70\x77\x5d\x5d\xf0\x3a\xfc\xe7\xf7\x91\x4a\x51\xb1\x0e\xb0\x25\x26\xcc\x80\xe2\xec\xc5\x58\xdb\x42\xaf\x60\x5f\xac\xbb\xbb\xb4\xc0\x5d\xf8\x50\x06\xff\xad\xba\x3a\x73\x35\x66\x7c\x67\xa8\xa4\xbc\x07\x7f\x60\xd2\xe2\x31\x64\x58\x30\x5f\x04\x67\x3f\x6d\xbb\x63\xc2\x48\x3a\xbf\xde\x84\xe9\x44\x43\x90\xdf\xe1\x96\x58\x34\xf4\x1e\x41\x4e\xc4\xef\xa3\x3c\x3f\x2f\xe9\xaa\xbb\x3f\xf1\xa1\xe9\x8e\x9a\xcb\x8e\xce\x3f\x20\x09\x05\x18\x43\xef\xf7\x29\xf2\x56\x26\xc4\xc8\x50\xab\x2f\x0c\xaf\xe9\xbc\x02\x1e\x4e\x0b\xee\xb6\xf1\x46\x55\xee\x37\xb9\x8f\xf6\xe9\x61\xc5\x4e\xe5\xdf\xf6\xf3\x60\x7f\x06\x00\x00\xff\xff\x6f\x69\xf9\xcf\x4a\x02\x00\x00")

func templatesOutputTfBytes() ([]byte, error) {
	return bindataRead(
		_templatesOutputTf,
		"templates/output.tf",
	)
}

func templatesOutputTf() (*asset, error) {
	bytes, err := templatesOutputTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/output.tf", size: 586, mode: os.FileMode(480), modTime: time.Unix(1540863722, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _templatesProviderTf = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\x8e\xc1\x0a\xc2\x30\x0c\x40\xef\xfd\x8a\x50\x3d\x28\x88\x7f\xe0\x41\x3c\x0b\xfe\xc1\x98\x5d\xa6\xc1\xad\x19\x69\xb6\x83\x63\xff\x2e\xed\x64\x1b\x03\xed\xa9\xe4\xbd\xd7\x66\x03\x17\xf6\x25\x3d\x5a\x41\xd0\x27\xc2\x95\x9c\x70\xe0\x52\xe1\xfc\x8e\xb3\x9b\x70\x47\x05\x8a\x69\xbe\x17\xb0\x79\x04\x52\x5b\xe8\x0d\x80\xab\x08\xbd\x66\x54\xc0\x78\x4e\x60\xb7\x7d\x97\xcb\x31\x59\xd9\x84\x07\x3b\xcb\x01\x9d\xa0\xfe\x94\x47\x9c\x82\xd0\xde\x83\x13\x6a\x94\xd8\xc7\x3f\x56\xc1\x0a\xa7\x44\xd1\xe7\x7f\x16\x9a\x70\x92\xd1\x77\x24\xec\x6b\xf4\x3a\xcb\x15\xf3\xab\x6d\x76\xb1\x59\xf0\x70\x80\xf9\x95\xc5\x7c\x3f\x58\x33\x98\x4f\x00\x00\x00\xff\xff\x7b\x5e\xe5\xc8\x47\x01\x00\x00")

func templatesProviderTfBytes() ([]byte, error) {
	return bindataRead(
		_templatesProviderTf,
		"templates/provider.tf",
	)
}

func templatesProviderTf() (*asset, error) {
	bytes, err := templatesProviderTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/provider.tf", size: 327, mode: os.FileMode(480), modTime: time.Unix(1540863722, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _templatesResource_groupTf = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x64\x8c\x41\x0a\xc2\x40\x0c\x45\xf7\x73\x8a\x4f\x74\x5b\x6f\xe0\xca\x83\x0c\xa1\x4d\x65\xa4\x9d\x94\x38\x29\x62\x99\xbb\x4b\x2d\x55\xc4\xec\xf2\xf2\xf2\x0e\xb8\x98\x70\x11\x30\x3a\xe9\xd9\x87\x02\x93\xbb\xba\xb5\x82\xab\xa9\x4f\xe1\xb3\x12\x3f\xdd\xc4\xc6\xb8\x93\xf8\x16\x08\x74\x4b\xb9\x53\xff\xe3\x4b\x00\x32\x8f\x82\x75\xce\xa0\xe3\x32\xb3\x9d\x7e\xad\x38\x99\xf4\xe9\x51\x9b\xed\x28\x79\x8e\xeb\x4b\x6d\xb6\x26\x05\x60\xd0\x96\x4b\xd2\xfc\x4d\xec\xa4\x52\xa8\xe1\x15\x00\x00\xff\xff\x8d\x05\xd8\x33\xc2\x00\x00\x00")

func templatesResource_groupTfBytes() ([]byte, error) {
	return bindataRead(
		_templatesResource_groupTf,
		"templates/resource_group.tf",
	)
}

func templatesResource_groupTf() (*asset, error) {
	bytes, err := templatesResource_groupTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/resource_group.tf", size: 194, mode: os.FileMode(480), modTime: time.Unix(1540863722, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _templatesVarsTf = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\x90\xcd\x4e\xeb\x30\x10\x85\xf7\x7e\x8a\x91\x1f\xe0\xde\xdb\xbb\x60\x97\x05\xea\xa2\x0f\x80\x58\x21\x64\x4d\x9d\x69\x18\x70\x6c\x6b\xc6\x0e\x3f\x55\xdf\x1d\x25\x2d\x90\xb4\x40\xb2\x1a\x9f\xcf\xc7\xe7\xcc\x80\xc2\xb8\x0d\x04\x96\xe2\xe0\x22\xf6\x64\x61\x7f\x30\x66\x71\xce\x92\x62\x4f\xb1\xa8\x85\xbd\x01\x28\xaf\x99\xa0\x01\xdb\x63\xb6\x06\xa0\xa5\x1d\xd6\x50\xa0\x99\x44\x80\xeb\xb7\x2a\xb4\x0e\xa9\xb6\x70\xfa\x1a\xb0\xb9\x6e\x03\x7b\xfb\x05\xdc\xde\x6c\xd2\x40\x32\xf9\x8e\x40\xd5\xee\x73\x9e\x61\x1b\x92\x1e\xe3\xc9\xad\x01\xdb\x4d\xf3\x0c\x58\x3f\x70\xc4\x8f\xd7\x1a\xb0\x7e\x9c\x47\xfd\x60\x16\x35\x70\x84\xdd\xac\xcc\x79\xcf\x23\x50\x28\x62\x2c\x8e\xdb\xef\x65\xad\x5b\xf5\xc2\xb9\x70\x8a\x3f\x42\x3e\x30\xfd\xe2\x71\x92\x95\xbc\xd0\x45\x0a\x21\x4d\x55\x3c\xb9\x4e\x52\xcd\x2e\x0b\xed\xf8\x65\xb6\xf6\x63\x49\x2d\xc2\xb1\x5b\x2e\xdf\xda\x65\xe1\x90\x3c\x8e\x31\x8f\x97\x67\x1c\xa1\x96\xaa\xff\xcf\xf0\x47\x8e\x6d\xaa\x6e\x60\x29\x15\x83\x8b\x54\x9e\x93\x3c\x39\x6c\x5b\x21\x55\xa7\x19\x3d\x5d\xe4\x08\xac\x65\x99\xe2\xce\xae\xfe\xfd\x99\xfe\xbf\xab\x2b\x7b\x6f\x0e\xe6\x3d\x00\x00\xff\xff\x9f\x9d\x7e\xe1\x62\x02\x00\x00")

func templatesVarsTfBytes() ([]byte, error) {
	return bindataRead(
		_templatesVarsTf,
		"templates/vars.tf",
	)
}

func templatesVarsTf() (*asset, error) {
	bytes, err := templatesVarsTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/vars.tf", size: 610, mode: os.FileMode(480), modTime: time.Unix(1540863722, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"templates/network.tf": templatesNetworkTf,
	"templates/output.tf": templatesOutputTf,
	"templates/provider.tf": templatesProviderTf,
	"templates/resource_group.tf": templatesResource_groupTf,
	"templates/vars.tf": templatesVarsTf,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"templates": &bintree{nil, map[string]*bintree{
		"network.tf": &bintree{templatesNetworkTf, map[string]*bintree{}},
		"output.tf": &bintree{templatesOutputTf, map[string]*bintree{}},
		"provider.tf": &bintree{templatesProviderTf, map[string]*bintree{}},
		"resource_group.tf": &bintree{templatesResource_groupTf, map[string]*bintree{}},
		"vars.tf": &bintree{templatesVarsTf, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

